<?php

/**
 * Show the Smile.io widget on the frontend. Since the widget should
 * only be shown when the extension is enabled and when the customer
 * is actually logged in, we do two checks before showing the code.
 */

use Mediact\Smile\Block\Script;

/** @var Script $block */
?>
<div id="smile-io" data-bind="scope: 'smileio'">
    <!-- ko if: customer().fullname  -->
    <script type="text/x-magento-init">
    {
        "#smile-io": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "smileio": {
                        "component": "Mediact_Smile/js/smile-io",
                        "template" : "Mediact_Smile/smile-io"
                    }
                }
            }
        }
    }
    </script>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <!-- /ko -->
</div>